### PR TITLE
Wrapper Upgrade and Tutorial

### PR DESCRIPTION
**Pull request by varunagrawal**
1. Reorganized some files to be semantically meaningful.
2. Updated the code to remove unnecessary things which don't provide much value.
3. Updated the Tutorial file.
4. Added more docstrings.

### CODE REVIEW

**Comment by ProfFan** [comment]
@varunagrawal It's your call now :)

**Comment by ProfFan** [comment]
@dellaert I think that is what we agreed on when wrapping GTSAM? We can remove the two `.h` files here if we do not use the opaque std wrapping provided by pybind11.

**Comment by varunagrawal** [comment]
So I was assuming that's what the `module.py` and the Ipython notebook were for: a main "script" to call the wrapped module.

The wrapped module is installed to the python namespace so we can do `import gtsam_example`, so I am not sure what you mean by a main file with argparse. What would the arguments be?

As for `.h` files in the Python folder, we need to update the wrapper example template in the `wrap` repository to not have the `specializations.h` and `preamble.h` includes. We can leave that to the user IMO since in this example they are just empty files.

**Comment by dellaert** [comment]
module.py is a module. It does not have a main. 
argparse is often used to pare command line arguments in a main file.
Maybe we should chat in person

**Review by dellaert — APPROVED** [review]
Why don’t we land now and we will fix organization after our meeting

**Pull request merged**
